name: hahuu_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <=3.3.2"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  hive: ^2.2.3
  path_provider: ^2.0.11
  change_app_package_name: ^1.1.0
  lottie: ^2.3.0
  flutter_animate: ^4.1.0
  platform_device_id: ^1.0.1
  dio: ^5.0.3
  validatorless: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/file/
    - assets/font/
    - assets/icons/
    - assets/icons/misc/
    - assets/images/avatar/
    - assets/images/illustration/
